Algoritmo "Exercicio 8"
//Desenvolva um algoritmo para calcular o valor do DELTA de uma equação.
//Sabe-se que a fórmula do delta é
//Fórmula delta = b^2 – 4 * a * c
Var
a,b,c,delta:real


Inicio
limpatela

Escreva("Informe o A :")
leia(a)

limpatela

Escreva("Informe o B :")
leia(b)

limpatela

Escreva("Informe o C :")
leia(c)
limpatela

delta:= b^2 – 4 * a * c

escreval("-----------------")
escreval("O Delta é: ",delta)
escreval("-----------------")
Fimalgoritmo