Algoritmo "Leitor de Valores"
//Ler dois valores para as variáveis A e B,
//e efetuar as trocas dos valores de forma que a variável A
//passe a possuir o valor
// da variável B e a variável B passe a possuir o valor da variável A.
//Apresentar os valores trocados.
Var
n1,n2,n3:real


Inicio
 escreva("Informe o Valor A: ")
 leia(n1)
 
limpatela

escreva("Informe o Valor B: ")
leia(n2)
n3:=n1
n1:= n2
n2:=n3
limpatela

escreval("Valor A: ",n1)
escreval("Valor B: ",n3)





Fimalgoritmo